modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="custom_background_music"
version="1.0.0"
displayName="Custom Background Music"
authors="Dash_Ketch"
logoFile = "logo.png"
description='''
A mod that allows you to upload and play custom music files as background music in Minecraft.
'''

[[dependencies.custom_background_music]]
modId="neoforge"
type="required"
versionRange="[21.1.10,)"
ordering="NONE"
side="CLIENT"

[[dependencies.custom_background_music]]
modId="minecraft"
type="required"
version="[21.1.10,)"
ordering="NONE"
side="CLIENT"